export const PATH = Object.freeze({
  ROOT: "/",
  HOME: "/home",
  JOB: "/home/jobs",
  COMMUNITY: "/home/community",
  COMPANY: "/home/companies",
  CV_BUILDER: "/home/cv-builder",
  LOGIN: "/home/login",
  SIGN_UP: "/home/sign-up",
  JOB_DETAIL: "/home/jobs/:id",
  PROFILE: "/home/profile",
  DASHBOARD: "/dashboard",
  POSTED_JOB: "/dashboard/posted-jobs",
  CANDIDATE_MANAGEMENT: "/dashboard/candidate-management",
  EMPLOYEE_MANAGEMENT: "/dashboard/employee-management",
  USER_MANAGEMENT: "/dashboard/user-management",
  AUTHORIZATION_SETTING: "/dashboard/authorization-setting",
  UNAUTHORIZED: "/unauthorized",
  FORBIDDEN: "/forbidden",
  NOT_FOUND: "/*",
});
